# Generated by Django 3.2.3 on 2021-05-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kabu_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kabu_db',
        ),
    ]
