version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/pydocker
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up

      - run:
          name: docker-compose stop
          command: |
            docker-compose stop