version: 2.1
jobs:   
  build:
    docker:
      - image: continuumio/miniconda3
      #- image: conda/miniconda3
      #- image: conda/miniconda3
      #- image: continuumio/anaconda3:2019.03
      - image: cimg/python:3.8
     
      #- image: cimg/conda
    working_directory: ~/django-rest-api-mystock-app
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apt-get update
            apt install -y curl
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: manage
          command: |
            pip install -r requirements.txt
            conda install -c conda-forge fbprophet
            conda uninstall pandas
            conda install pandas==1.2.4
            python manage.py runserver
            