version: 2.1
jobs:   
  build:
    docker:
      #- image: continuumio/miniconda3
      #- image: conda/miniconda3
      #- image: conda/miniconda3
      - image: continuumio/anaconda3:2019.03
      - image: cimg/python:3.8
     
      #- image: cimg/conda
    working_directory: ~/django-rest-api-mystock-app
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apt-get update
            apt install -y curl
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Preparation
          command: |
            pip install -r requirements.txt
            conda install -c conda-forge fbprophet
            mv -f hdays.py /opt/conda/lib/python3.7/site-packages/fbprophet
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
            
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
            